### ISSUE TITLE
Improve automated data

### ISSUE THREAD

**Issue by adamf321** [moxie-lean/wp-endpoints-post#10]
There is some extra data we could include automatically, maybe using filters to control whether or not they are sent. Eg:

- Featured image
- Author
- Category / taxonomy values
- Date / time

**Comment by jeffreynolte** [comment]
@adamf321 - we should probably create a gist for this issue as this project is open but the referenced project is internal.

**Comment by mitogh** [comment]
Reference: https://gist.github.com/mitogh/9a9e16df9a9fd5c187eb0c4e48939bea

**Comment by adamf321** [comment]
Thanks Cris

**Comment by adamf321** [comment]
Also see https://github.com/moxie-leean/wp-endpoints-collection/blob/master/src/Collection.php
